// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package message

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type MessagesSource string

const (
	MessagesSourceEmail MessagesSource = "email"
)

func (e *MessagesSource) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MessagesSource(s)
	case string:
		*e = MessagesSource(s)
	default:
		return fmt.Errorf("unsupported scan type for MessagesSource: %T", src)
	}
	return nil
}

type NullMessagesSource struct {
	MessagesSource MessagesSource
	Valid          bool // Valid is true if MessagesSource is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMessagesSource) Scan(value interface{}) error {
	if value == nil {
		ns.MessagesSource, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MessagesSource.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMessagesSource) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MessagesSource), nil
}

type MessagesStatus string

const (
	MessagesStatusPending    MessagesStatus = "pending"
	MessagesStatusComplete   MessagesStatus = "complete"
	MessagesStatusClassified MessagesStatus = "classified"
	MessagesStatusFailed     MessagesStatus = "failed"
)

func (e *MessagesStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MessagesStatus(s)
	case string:
		*e = MessagesStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for MessagesStatus: %T", src)
	}
	return nil
}

type NullMessagesStatus struct {
	MessagesStatus MessagesStatus
	Valid          bool // Valid is true if MessagesStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMessagesStatus) Scan(value interface{}) error {
	if value == nil {
		ns.MessagesStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MessagesStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMessagesStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MessagesStatus), nil
}

type Message struct {
	ID        int64
	UserID    int64
	MessageID string
	Source    MessagesSource
	Status    MessagesStatus
	UpdatedAt pgtype.Timestamp
	CreatedAt pgtype.Timestamp
}
