// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package message

import (
	"context"
)

const createMessage = `-- name: CreateMessage :exec
INSERT INTO messages (user_id, message_id, source) VALUES ($1, $2, $3)
`

type CreateMessageParams struct {
	UserID    int64
	MessageID string
	Source    MessagesSource
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) error {
	_, err := q.db.Exec(ctx, createMessage, arg.UserID, arg.MessageID, arg.Source)
	return err
}

const getMessageByExternalId = `-- name: GetMessageByExternalId :one
SELECT id, user_id, message_id, source, status, updated_at, created_at FROM messages WHERE message_id = $1
`

func (q *Queries) GetMessageByExternalId(ctx context.Context, messageID string) (Message, error) {
	row := q.db.QueryRow(ctx, getMessageByExternalId, messageID)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.MessageID,
		&i.Source,
		&i.Status,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}
