// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package action

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type ActionType string

const (
	ActionTypeCreateReminder                    ActionType = "create_reminder"
	ActionTypeGetAllReminders                   ActionType = "get_all_reminders"
	ActionTypeDeleteReminder                    ActionType = "delete_reminder"
	ActionTypeUpdateUserTimezone                ActionType = "update_user_timezone"
	ActionTypeUpdateUserCommunicationPreference ActionType = "update_user_communication_preference"
	ActionTypeUpdateUserName                    ActionType = "update_user_name"
	ActionTypeUnknown                           ActionType = "unknown"
)

func (e *ActionType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ActionType(s)
	case string:
		*e = ActionType(s)
	default:
		return fmt.Errorf("unsupported scan type for ActionType: %T", src)
	}
	return nil
}

type NullActionType struct {
	ActionType ActionType
	Valid      bool // Valid is true if ActionType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullActionType) Scan(value interface{}) error {
	if value == nil {
		ns.ActionType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ActionType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullActionType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ActionType), nil
}

type Action struct {
	ID        int64
	Type      ActionType
	MessageID int64
	Payload   []byte
	Completed bool
	UpdatedAt pgtype.Timestamp
	CreatedAt pgtype.Timestamp
}
