// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package action

import (
	"context"
)

const getRemindersForEmail = `-- name: GetRemindersForEmail :many
SELECT id, type, message_id, payload, completed, updated_at, created_at FROM actions WHERE message_id = $1
`

func (q *Queries) GetRemindersForEmail(ctx context.Context, messageID int64) ([]Action, error) {
	rows, err := q.db.Query(ctx, getRemindersForEmail, messageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Action
	for rows.Next() {
		var i Action
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.MessageID,
			&i.Payload,
			&i.Completed,
			&i.UpdatedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
